name: .NET

on:
  release:
    types: [published]

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fetch history
      run: git fetch --prune --unshallow
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
           9.0.x
    - name: Restore dependencies
      run: |
        dotnet restore OrcaSql.slnx

    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        version: ${{ github.event.release.tag_name }}
        assemblyVersion: ${{ github.event.release.tag_name }}
        fileVersion: ${{ github.event.release.tag_name }}
        informationalVersion: ${{ github.event.release.tag_name }}-${{ github.sha }}
    
    - name: Build
      run: |
        dotnet build -c Release OrcaSql.slnx
        
    - name: Upload to release
      uses: AButler/upload-release-assets@v3.0
      with:
        files: 'src/OrcaSql.Core/bin/Release/netstandard2.0/OrcaSql.Core.dll"'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to release
      uses: AButler/upload-release-assets@v3.0
      with:
        files: 'src/OrcaSql.RawCore/bin/Release/netstandard2.0/OrcaSql.RawCore.dll"'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to release
      uses: AButler/upload-release-assets@v3.0
      with:
        files: 'src/OrcaSql.Framework/bin/Release/netstandard2.0/OrcaSql.Framework.dll"'
        repo-token: ${{ secrets.GITHUB_TOKEN }}